# We follow [this tutorial](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-community-with-docker/):
pull-mongo:
	docker pull mongodb/mongodb-community-server:latest

run-mongo:
	docker run --name mongodb -p 27017:27017 -d mongodb/mongodb-community-server:latest

